# Generated by Django 3.0.8 on 2020-07-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourisam',
            name='city_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
